replicaCount: 1

image:
  repository: <YOUR ECR REPO>
  tag: <YOUR TAG>
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

env:
  DD_SERVICE: "my-python-service"
  DD_ENV: "staging"
  DD_LOGS_INJECTION: "true"

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}

